### ISSUE TITLE
Consider enforcing unique test names

### ISSUE THREAD

**Issue by halfzebra** [trustpilot/skift#22]
It is possible to have multiple tests with the same name.

`skift.getTest` will return only the first test in the list.

I would expect to retrieve a list of tests with the same name.

@thomicdk what do you think?

If tests have the same name and one of the tests is initialized, then the other one should get the same variant(if present)

Otherwise, it should warn or maybe crash?

On the second thought, I would consider disallowing having two tests with the same name.

**Comment by thomicdk** [comment]
The original intention was keep the test name unique and thus disallow multiple tests with the same name.

But keep in mind that tests live in the scope of a page, so you are allowed to reuse test names across pages. This is quite useful, if you want to test something that spans multiple pages. 
For now however, this only works in a MPA where each page load ensures existing tests are automatically teared down. For a SPA we might need to make additions. I imagine you would call an API like this: `skift.tearDown()`:

Example in an Angular application:
```javascript
$scope.$on('$locationChangeStart', function( event ) {
    skift.tearDown();
});
```
In each test you could optionally subscribe to `onTearDown`:
```javascript
skift
  .create('My test')
  .onTearDown(() => {
    // Clean up ...
  });
```
@halfzebra what do you think?

**Comment by halfzebra** [comment]
@thomicdk I can think of two primary use-cases:

* We keep the option to create tests with the same name, this opens up an opportunity for having two tests with the same name in the same runtime. In that case, we have to ensure, that the second test will get the same variant as the first one if it's present. Otherwise, it should warn the user or maybe crash.

* We enforce unique names and then one test is supposed to be shared across the pages, this does apply to SPA and SSR apps.

I'm not sure if the option to cleanup will solve the issue, I guess I'm missing something.

Let's have a chat and see what's possible 🙂 

The name of this issue is not resembling the cause, so I'll change it.

**Comment by halfzebra** [comment]
Looks like this idea is not as viable as it seemed, I'm closing it.
