### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by halfzebra** [trustpilot/skift#28]
We need a folder with working examples, where users can learn Skift by example.

There's some work done in #27

I'd love to have an example of integration with Amplitude.

@thomicdk thoughts?

**Comment by thomicdk** [comment]
Examples, yes! That was exactly what I had in mind when I suggested an alternative folder structure in #27. 

I would be happy to add an example showing Segment/Amplitude integration, once #27 has been merged.

**Comment by halfzebra** [comment]
@thomicdk I have altered the folder structure, there's one example so far.

I think we need an example or a guide for setting up the entire reporting pipeline.

**Comment by halfzebra** [comment]
Closing this due to the lack of interest!

Have a nice day! 🙂
